openapi: 3.1.0
info:
  version: 1.0.0
  title: <Contacts>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <This is a documentation of contacts app>
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  # - url: http://example.com/api/v1
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/logout.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
